### ISSUE TITLE
Remove Dean's email address and add community manager email address

### ISSUE THREAD

**Issue by BigActual** [VLSLgithub/VL-theme-V1#79]
Please remove Dean's email address from the footer and on Community specific pages please add the email address for the Community Executive Director.

- creese@vibrantlifetemperance.com        Temperance
- jbirchmeier@thelodgeofdurand.com       Durand
- abuhl@newfriendsmemorycare.com       Kalamazoo
- ahanson@vibrantlifesuperior.com             Superior 

Instead of putting those addresses at the bottom of the entire footer, please place them above the corporate information and space them into the mix nicely, so that they look like they belong with the community information already displayed in the footer of each community page.

**Comment by d4mation** [comment]
I've updated the email addresses for each of the communities. Dean's Email is showing because he's listed for the "Corporate Office". That can be edited here: https://vibrantlifeseniorliving.com/wp-admin/admin.php?page=edit-agile-store&store_id=5

Email is listed a bit lower because normally it would go:

```
Phone:
Fax:

Email:
```

Should that extra line break be removed? 

On Community pages, it shows the Community Address block followed by the Corporate Address block.

**Comment by d4mation** [comment]
@BigActual I see that you removed Dean's email from the Corporate Office listing. Is anything else needed to be done for this Issue, or is it good to close out?

**Comment by BigActual** [comment]
All set
